name: get_work_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  provider: ^6.1.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.1
  pdfrx: ^1.2.0
  image: ^4.1.3
  photo_view: ^0.15.0
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  http: ^1.4.0
  flutter_dotenv: ^5.1.0
  open_file: ^3.5.10
  intl: ^0.20.2
  cloudinary: ^1.2.0
  file_selector: ^1.0.3
  fl_chart: ^0.65.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env